# This file was generated by GoReleaser. DO NOT EDIT.
cask "schnappit" do
  name "schnappit"
  desc "A macOS screenshot utility"
  homepage "https://github.com/owenrumney/schnappit"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "schnappit"

  on_macos do
    on_arm do
      url "https://github.com/owenrumney/schnappit/releases/download/v#{version}/schnappit_#{version}_darwin_arm64.zip"
      sha256 "d6e3b29526848fe74372375ba53cadf7d51e93eaa346b3145ba4297aad156853"
    end
  end

  postflight do
    # Remove quarantine attribute to avoid Gatekeeper issues
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{staged_path}/schnappit"],
                   sudo: false
  end

  # No zap stanza required
end
